export default class Clubs {
	facilityID?: string;
	club_name?: string;
	club_membership?: string;
	holes?: string;
	address?: string;
	city?: string;
	state?: string;
	country?: string;
	continent?: string;	
	postal_code	?: string;
	phone?: string;
	fax?: string;
	website?: string;
	longitude?: string;
	latitude?: string;
	contact_name?: string;
	contact_title?: string;
	email?: string;
	driving_range?: boolean;
	putting_green?: boolean;
	chipping_green?: boolean;
	practice_bunker?: boolean;
	motor_cart?: boolean;
	pull_cart?: boolean;
	golf_club_rentals?: boolean;	
	club_fitting?: boolean;
	pro_shop?: boolean;
	golf_lessons?: boolean;
	caddie_hire	?: boolean;
	restaurant?: boolean;
	reception_hall?: boolean;
	changing_room?: boolean;
	lockers?: boolean;
	lodging_on_site?: boolean;
}
